# Generated by Django 4.2.17 on 2024-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_variety', models.CharField(max_length=200, null=True)),
                ('gst', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
